version: '3'
services:
  client:
    container_name: dev_client
    build: ./client
    image: debug_client
    ports: 
      - 8080:8080
    working_dir: /code
    volumes:
      - type: bind
        source: ./client
        target: /code
    command: [ "http-server" ]
  server:
    build:
      dockerfile: Dockerfile
    container_name: dev_server
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=user
      - PGHOST=db
      - PGPASSWORD=dataforSQLpassword
      - PGDATABASE=dataforSQL
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run start"
  db:
    image: postgres:latest
    volumes:
      - "dbdata:/var/lib/postgresql/data"
      - "./db:/docker-entrypoint-initdb.d/:ro"
    environment: 
      - POSTGRES_DB=dataforSQL
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dataforSQLpassword
volumes:
  dbdata:
networks: 
  default:
    name: app_dev
