services:
  api:
    container_name: demo_test_api
    environment: 
      - PGUSER=user
      - PGHOST=db
      - PGPASSWORD=userpass
      - PGDATABASE=user_test
      - PGPORT=5432
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
  db:
    container_name: test_db
    volumes:
      - "test_db:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=user_test
      - POSTGRES_PASSWORD=userpass
volumes:
  test_db:
networks: 
  default:
    name: app_test
